### ISSUE TITLE
RSS returns truncated title and description

### ISSUE THREAD

**Issue by ThomasJRyan** [kevinodotnet/ottwatch#78]
Hi there! I just want to start off by saying this is a really awesome project and I'm glad it exists! Doubly so that it provides an RSS feed that I can quickly and easily pull the latest announcements from!

There's just one thing... The title and description that get passed back are truncated just as they're shown on the homepage.

Ex:
```xml
<item>
  <title>DevApp D02-02-23-0065 (Zoning By-law Amendment for 5134 PIPERVILLE) has been born: To rezone the severed lands to satisfy a condition of provisional consent. At the time of consent (D08-01-22/B-00296)...</title>
  <description>5134 PIPERVILLE Road: DevApp::Entry</description>
  <pubDate>Mon, 14 Aug 2023 20:35:11 +0000</pubDate>
  <link>https://ottwatch.ca/devapp/D02-02-23-0065</link>
  <guid>https://ottwatch.ca/announcement/6493</guid>
</item>
```
and
```xml
<item>
  <title>Additional Lobbying activity</title>
  <description>Danya Vered (Vice President): To assist our client in sorting out requirements for building ...: LobbyingUndertaking</description>
  <pubDate>Fri, 11 Aug 2023 13:45:24 +0000</pubDate>
  <link>https://ottwatch.ca/lobbying/4346</link>
  <guid>https://ottwatch.ca/announcement/6483</guid>
</item>
```
It would be great if they were either not truncated or there was an option to toggle the truncation! I'd open a PR to make the change myself, but Ruby is very far outside my knowledge scope... I'm sorry to ask this of you, but if it's at all possible to provide non-truncated information I would seriously appreciate it! Thank you!

**Comment by kevinodotnet** [comment]
hi! thanks for the issue reports!

**Comment by kevinodotnet** [comment]
The truncation is a cheap hack from the truncation I built for twitter syndication. Should be a really easy update

**Comment by kevinodotnet** [comment]
Hmm, it's actually a little harder than I thought, mainly because `Announcement` is a generic bucket for context, and I don't want to overload it with duplication of data.

What if I updated `link` to point to a JSON version of the same artifact? 

Then you could pull the RSS, then get `https://ottwatch.ca/devapp/D02-02-23-0065.JSON` (the ".json" is new), and that returns well structured data about the "thing" that is being announced? Then I can dump all the context out, such as: 

- all the addresses for a devapp; and the history of all state changes
- the full text of a lobbying registry? 

That keeps the RSS feed focused on `syndication` but is not itself a full repository of data

**Comment by kevinodotnet** [comment]
I'm going to leave this one as it is. Maybe re-visit after I overhaul announcements completely. I'm happy with this as "good enough" for now
